### ISSUE TITLE
expressif-esp32-c6-devkitc-1: first flash issue

### ISSUE THREAD

**Issue by emmanuelsearch** [future-proof-iot/RIOT-rs#200]
after installing the toolchain as suggested by an initial buidling error with: 

rustup component add rust-src --toolchain nightly-2024-03-11-x86_64-unknown-linux-gnu

I run into the below error:

Running `probe-rs run --chip '${PROBE_RS_CHIP}' ../../build/bin/expressif-esp32-c6-devkitc-1/hello-world/cargo/riscv32imac-unknown-none-elf/release/hello-world`
Error: The chip '${PROBE_RS_CHIP}' was not found in the database.

Caused by:
    The requested chip '${PROBE_RS_CHIP}' was not found in the list of known targets.

**Comment by kaspar030** [comment]
Thanks!

This is b/c the esps don't use probe-rs, but the README.md since #195 incorrectly states that replacing the board name is enough to use the same command line for all boards.

The real fix here is to just default to probe-rs-run for boards supporting that, and dropping the use in the command line. Will get to that.
